name: EasyEssentials
version: ${project.version}
main: com.preston.essentials.Essentials
author: [preston]
description: Light-Weight Essentials plugin without uneccessary stuff of original plugin.

commands:
  gm:
    description: Shortcut for /gamemode command.
    usage: /gm <0|1|2|3|survival|creative|adventure|spectator> [player]
    permission: easyessentials.gm

permissions:
  easyessentials.gm:
    description: Allows the player to change their own gamemode via /gm.
    default: op
  easyessentials.gm.other:
    description: Allows the player to change another player's gamemode via /gm.
    default: op
