name: Basic
version: ${project.version}
main: com.preston.basic.Basic
author: [preston]
description: Light-Weight Essentials plugin without uneccessary stuff of original plugin.

commands:
  gm:
    description: Shortcut for /gamemode command.
    usage: /gm <0|1|2|3|survival|creative|adventure|spectator> [player]
    permission: basic.gm

permissions:
  basic.gm:
    description: Allows the player to change their own gamemode via /gm.
    default: op
  basic.gm.other:
    description: Allows the player to change another player's gamemode via /gm.
    default: op
